services:
  portainer:
    image: outlovecn/portainer-cn
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/docker/portainer/data:/data
