services:
  moontv:
    image: ghcr.io/moontechlab/lunatv:latest
    container_name: moontv
    restart: always
    ports:
      - '8096:3000'
    environment:
      - USERNAME=admin
      - PASSWORD=s19194
      - NEXT_PUBLIC_STORAGE_TYPE=kvrocks
      - KVROCKS_URL=redis://moontv-kvrocks:6666
    networks:
      - moontv-network
    depends_on:
      - moontv-kvrocks
  moontv-kvrocks:
    image: apache/kvrocks
    container_name: moontv-kvrocks
    restart: always
    volumes:
      - kvrocks-data:/var/lib/kvrocks
    networks:
      - moontv-network
networks:
  moontv-network:
    driver: bridge
volumes:
  kvrocks-data:
