services:
  openlist:
    image: 'openlistteam/openlist:latest'
    container_name: openlist
    volumes:
      - '/root/docker/alist/data:/opt/openlist/data'
      - '/mnt:/share'
    ports:
      - '5244:5244'
    restart: unless-stopped
